version: '3.4'

services:
  quizapp.api:
    image: ${DOCKER_REGISTRY-}quizappapi
    environment:
      - QuizAppDatabase__ConnectionString=mongodb://quizDB
    build:
      context: .
      dockerfile: QuizApp.API/Dockerfile

  quizapp.db:
    container_name: quizDB
    ports:
      - 27017:27017
    image: mongo:8.0.1
    volumes:
      - quizapp_mongodb:/etc/mongo

volumes:
  quizapp_mongodb:
