# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.x
    - name: Restore dependencies
      run: dotnet restore QuizApp.Backend.slnx
    - name: Build
      run: dotnet build QuizApp.Backend.slnx --no-restore
    - name: Test
      run: dotnet test QuizApp.Backend.slnx --no-build --verbosity normal /p:CollectCoverage=true
            /p:CoverletOutput=TestResults/coverage.lcov /p:CoverletOutputFormat=lcov
    - name: Publish coverage report to coveralls.io     
      uses: coverallsapp/github-action@v2
      with:
        file: QuizApp.Tests/TestResults/coverage.lcov
        format: lcov
        github-token: ${{ secrets.GITHUB_TOKEN }} 
