# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.x
    - name: Restore dependencies
      run: dotnet restore QuizApp.Backend.sln
    - name: Build
      run: dotnet build QuizApp.Backend.sln --no-restore
    - name: Test
      run: dotnet test QuizApp.Backend.sln --no-build --verbosity normal /p:CollectCoverage=true
            /p:CoverletOutput=TestResults/ /p:CoverletOutputFormat=lcov
    - name: Publish coverage report to coveralls.io     
      uses: coverallsapp/github-action@v2.2.3 
      with:
        file: QuizApp.Tests/TestResults/coverage.info
        github-token: ${{ secrets.GITHUB_TOKEN }} 
